name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Build and test in Docker
      run: |
        docker build -t rocksdb-cli-test -f Dockerfile.test .
        docker run --rm rocksdb-cli-test
    
    - name: Extract coverage report
      run: |
        # Create a temporary container to extract coverage report
        docker create --name temp-test rocksdb-cli-test
        docker cp temp-test:/app/coverage.html ./coverage.html 2>/dev/null || echo "No coverage report found"
        docker rm temp-test
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage.html 