name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Install RocksDB dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          librocksdb-dev \
          libsnappy-dev \
          liblz4-dev \
          libzstd-dev \
          libbz2-dev \
          zlib1g-dev
    
    - name: Set up CGO environment
      run: |
        echo "CGO_CFLAGS=-I/usr/include" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=-L/usr/lib/x86_64-linux-gnu -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd" >> $GITHUB_ENV
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run unit tests
      run: go test ./... -v -race -coverprofile=coverage.out
    
    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.html 